# Reusable implementation macros. User-facing targets remain declared in the
# main Makefile so simple shell completion parsers can discover them.

_make = $(MAKE) --no-print-directory $(1)

# $(call _require_var,name,value,hint)
define _require_var
	@if [ -z "$(strip $(2))" ]; then echo "[ERR] $(3)"; exit 1; fi
endef

# $(call _require_file,path,hint)
define _require_file
	@if [ ! -f "$(1)" ]; then echo "[ERR] $(2)"; exit 1; fi
endef

# $(call _emit_fpga_image,out,stage_bin,payload,dtb_offset,dtb_src,label)
define _emit_fpga_image
@if [ -z "$(3)" ] || [ ! -f "$(3)" ]; then \
	echo "[ERR] $(6) payload not found: $(3)"; exit 1; fi; \
stage_size=$$(stat -c%s "$(2)"); \
payload_size=$$(stat -c%s "$(3)"); \
dtb_size=$$(stat -c%s "$(FW_LINUX_FPGA_DTB)"); \
payload_offset=$$(( $(LINUX_FPGA_PAYLOAD_OFFSET) )); \
dtb_offset=$$(( $(4) )); \
if [ $$stage_size -gt $$payload_offset ]; then \
	echo "[ERR] stage0 too large ($$stage_size > payload offset $$payload_offset)"; exit 1; fi; \
if [ $$((payload_offset + payload_size)) -gt $$dtb_offset ]; then \
	echo "[ERR] $(6) payload overlaps DTB slot ($$payload_size bytes, offset $$payload_offset, dtb offset $$dtb_offset)"; exit 1; fi; \
cp "$(2)" "$(1)"; \
truncate -s $$payload_offset "$(1)"; \
cat "$(3)" >> "$(1)"; \
truncate -s $$dtb_offset "$(1)"; \
cat "$(FW_LINUX_FPGA_DTB)" >> "$(1)"; \
image_size=$$(stat -c%s "$(1)"); \
echo "[INFO] $(6) image: $(1) ($$image_size bytes)"; \
echo "[INFO]   stage0  @ $(MAIN_RAM_BASE) size=$$stage_size"; \
echo "[INFO]   payload @ $(LINUX_FPGA_PAYLOAD_SRC_ADDR) -> $(MAIN_RAM_BASE) size=$$payload_size"; \
echo "[INFO]   dtb     @ $(5) -> $(LINUX_FPGA_DTB_ADDR) size=$$dtb_size"
endef

define _litex_bios_patches_apply
	$(PYTHON) $(LITEX_DIR)/scripts/patch_litex_picolibc.py $(LITEX_PATH) && $(PYTHON) $(LITEX_DIR)/scripts/patch_litex_uart_polling.py $(LITEX_PATH) && $(PYTHON) $(LITEX_DIR)/scripts/patch_litex_sdcard_boot.py $(LITEX_PATH)
endef

define _litex_bios_patches_restore
	cd $(LITEX_PATH) && git checkout -- litex/soc/software/common.mak litex/soc/software/libc/Makefile litex/soc/software/libbase/uart.c litex/soc/software/bios/main.c 2>/dev/null || true
endef

# $(call _run_litex_target,arguments)
define _run_litex_target
if [ "$(BOOT_MODE)" = "bios" ]; then $(call _litex_bios_patches_apply); fi; \
trap '[ "$(BOOT_MODE)" = "bios" ] && { $(call _litex_bios_patches_restore); } || true' EXIT; \
source $(VENV_DIR)/bin/activate && \
$(PYTHON) $(FPGA_PY) $(1)
endef

define _soc_gen
	source $(VENV_DIR)/bin/activate && \
	$(PYTHON) raptor_soc.py $(1) $(EXTRA_FLAGS)
endef

define _compile_if_needed
	@mkdir -p $(1)
	@SIM_V_HASH=$$({ \
		grep -v -e '^// Date' -e '^//  Auto-Generated by LiteX on' $(1)/sim.v 2>/dev/null; \
		cat $(1)/sim_init.cpp 2>/dev/null; \
		cat $(1)/build_sim.sh 2>/dev/null; \
		cat $(PACK_SV) 2>/dev/null; \
	} | md5 -q 2>/dev/null || { \
		grep -v -e '^// Date' -e '^//  Auto-Generated by LiteX on' $(1)/sim.v 2>/dev/null; \
		cat $(1)/sim_init.cpp 2>/dev/null; \
		cat $(1)/build_sim.sh 2>/dev/null; \
		cat $(PACK_SV) 2>/dev/null; \
	} | md5sum | cut -d' ' -f1); \
	OLD_HASH=$$(cat $(1)/.sim_v_hash 2>/dev/null || echo ""); \
	if [ ! -f $(1)/obj_dir/Vsim ] || [ "$$SIM_V_HASH" != "$$OLD_HASH" ]; then \
		echo "[INFO] Compiling Verilator simulation (this may take several minutes)..."; \
		cd $(1) && bash build_sim.sh; \
		echo "$$SIM_V_HASH" > $(1)/.sim_v_hash; \
		echo "[INFO] Verilator compilation complete."; \
	else \
		echo "[INFO] Verilator binary up to date, skipping compilation."; \
	fi
endef

define _run_vsim
	@if [ ! -f $(1)/obj_dir/Vsim ]; then \
		echo "[ERR] No sim binary at $(1). Run 'make sim-build' first."; exit 1; fi
	@echo "[INFO] Running sim (timeout=$(SIM_TIMEOUT)s, Ctrl+C to stop)"
	@if [ -n "$(TRACE_MSG)" ]; then echo "[INFO] $(TRACE_MSG) — wave -> $(1)/sim.$(TRACE)"; fi
	@cd $(1) && \
	if [ -z "$(SIM_STOP_MARKER)" ]; then \
		$(TIMEOUT_RUN) $(TIMEOUT_FOREGROUND) $(SIM_TIMEOUT) obj_dir/Vsim; \
		rc=$$?; \
		if [ $$rc -eq 124 ]; then \
			echo ""; echo "[INFO] Simulation timed out after $(SIM_TIMEOUT)s."; \
		elif [ $$rc -eq 130 ] || [ $$rc -eq 143 ]; then \
			echo ""; echo "[INFO] Simulation interrupted (Ctrl+C / SIGTERM)."; \
		elif [ $$rc -ne 0 ]; then \
			exit $$rc; \
		fi; \
	else \
		: > sim_run.log; \
		obj_dir/Vsim > sim_run.log 2>&1 & vpid=$$!; \
		tail -n +1 -f sim_run.log 2>/dev/null & tpid=$$!; \
		limit=$(SIM_TIMEOUT); [ "$$limit" = "0" ] && limit=100000; i=0; \
		while kill -0 $$vpid 2>/dev/null; do \
			if grep -qF "$(SIM_STOP_MARKER)" sim_run.log; then \
				echo "[INFO] Sim reached completion marker ('$(SIM_STOP_MARKER)')."; break; fi; \
			i=$$((i+1)); \
			if [ $$i -ge $$limit ]; then echo ""; echo "[INFO] Simulation timed out after $(SIM_TIMEOUT)s."; break; fi; \
			sleep 1; \
		done; \
		kill $$vpid 2>/dev/null || true; sleep 0.3; \
		for _ in 1 2 3 4 5; do kill -0 $$vpid 2>/dev/null || break; sleep 0.2; done; \
		kill -9 $$vpid 2>/dev/null || true; wait $$vpid 2>/dev/null || true; \
		kill $$tpid 2>/dev/null || true; wait $$tpid 2>/dev/null || true; \
	fi
	@if [ -n "$(TRACE_MSG)" ] && [ -f $(1)/sim.$(TRACE) ]; then \
		sz=$$(wc -c < $(1)/sim.$(TRACE)); \
		echo "[INFO] Wave: $(1)/sim.$(TRACE) ($$sz bytes)"; \
	fi
endef
# ==============================================================================
# Target implementations
# ==============================================================================

setup:
	@bash setup_env.sh

setup-skip:
	@bash setup_env.sh --skip-install

$(VENV_DIR)/bin/activate:
	@echo "[INFO] Run 'make setup' first to create the virtual environment."
	@exit 1

$(CHISEL_GENERATED_SRCS) &: $(CHISEL_INPUTS)
	$(MAKE) -C $(CHISEL_DIR) verilog

pack:
	$(MAKE) -C $(NSIM_DIR) pack RAPT_CONFIG=$(RAPT_CONFIG) VFLAGS="$(RAPT_PACK_VFLAGS)" CONFIG_MODE=

$(PACK_SV): $(RTL_SOURCES) $(RAPT_CONFIG_STAMP) $(RAPT_PACK_VFLAGS_STAMP)
	$(MAKE) -C $(NSIM_DIR) pack RAPT_CONFIG=$(RAPT_CONFIG) VFLAGS="$(RAPT_PACK_VFLAGS)" CONFIG_MODE=

$(FW_SIM_DIR):
	@mkdir -p $@

$(FW_SIM_DTB): $(FW_SIM_DTS) | $(FW_SIM_DIR)
	dtc -I dts -O dtb -o $@ $<

$(FW_SIM_ELF): $(FW_SIM_SRC)/boot.S $(FW_SIM_SRC)/link.ld $(FW_SIM_DTB) | $(FW_SIM_DIR)
	$(CROSS)gcc -march=rv32imac -mabi=ilp32 -nostdlib -nostartfiles -fno-pic -no-pie \
		-T $(FW_SIM_SRC)/link.ld -I$(FW_SIM_DIR) -o $@ $(FW_SIM_SRC)/boot.S

$(FW_SIM_BIN): $(FW_SIM_ELF)
	$(CROSS)objcopy -O binary $< $@

$(FW_FPGA_DIR):
	@mkdir -p $@

$(FW_FPGA_DIR)/boot.o: $(FW_FPGA_SRC)/boot.S | $(FW_FPGA_DIR)
	$(CROSS)gcc $(FW_FPGA_CFLAGS) -c -o $@ $<

$(FW_FPGA_DIR)/main.o: $(FW_FPGA_MAIN_SRC) | $(FW_FPGA_DIR)
	$(CROSS)gcc $(FW_FPGA_CFLAGS) -c -o $@ $<

$(FW_FPGA_ELF): $(FW_FPGA_OBJS) $(FW_FPGA_LINK)
	$(CROSS)gcc $(FW_FPGA_CFLAGS) -Wl,--gc-sections -no-pie \
		-T $(FW_FPGA_LINK) -o $@ $(FW_FPGA_OBJS)

$(FW_FPGA_BIN): $(FW_FPGA_ELF)
	$(CROSS)objcopy -O binary $< $@

firmware-clean:
	rm -rf $(BUILD_DIR)/firmware
	@# Legacy in-tree artifacts from older versions of this Makefile:
	rm -f $(FW_SIM_SRC)/boot.elf $(FW_SIM_SRC)/boot.bin $(FW_SIM_SRC)/litex-soc.dtb

$(FW_LINUX_FPGA_DIR):
	@mkdir -p $@

$(FW_EGOS_STAGE0_DIR):
	@mkdir -p $@

$(FW_EGOS_STAGE0_ELF): $(FW_EGOS_STAGE0_SRC)/boot.S $(FW_EGOS_STAGE0_SRC)/link.ld | $(FW_EGOS_STAGE0_DIR)
	$(CROSS)gcc -march=rv32imac_zicsr_zifencei -mabi=ilp32 -nostdlib -nostartfiles \
		-fno-pic -no-pie -Wl,--build-id=none -T $(FW_EGOS_STAGE0_SRC)/link.ld -o $@ $<

$(FW_EGOS_STAGE0_BIN): $(FW_EGOS_STAGE0_ELF)
	$(CROSS)objcopy -O binary $< $@

$(FW_LINUX_FPGA_DTS): $(FW_LINUX_FPGA_DTS_IN) FORCE | $(FW_LINUX_FPGA_DIR)
	sed -e 's/@TIMEBASE@/$(SYS_CLK)/g' \
	    -e 's/@MEM_SIZE@/$(LINUX_FPGA_RAM_SIZE)/g' \
	    -e 's/@UART_BASE@/$(LINUX_FPGA_UART_BASE)/g' \
	    -e 's/@UART_UNIT_ADDR@/$(LINUX_FPGA_UART_UNIT_ADDR)/g' \
	    -e 's/@CBOM_BLOCK_SIZE@/$(RAPT_CACHE_LINE_BYTES)/g' \
	    $< > $@

$(FW_LINUX_FPGA_DTB): $(FW_LINUX_FPGA_DTS) | $(FW_LINUX_FPGA_DIR)
	dtc -I dts -O dtb -o $@ $<

$(FW_LINUX_FPGA_ELF): $(FW_LINUX_FPGA_SRC)/boot.S $(FW_LINUX_FPGA_SRC)/link.ld $(FW_LINUX_FPGA_DTB) $(LINUX_FPGA_PAYLOAD) | $(FW_LINUX_FPGA_DIR)
	@if [ -z "$(LINUX_FPGA_PAYLOAD)" ] || [ ! -f "$(LINUX_FPGA_PAYLOAD)" ]; then \
		echo "[ERR] Linux FPGA payload not found after linux-build: $(LINUX_FPGA_PAYLOAD)"; exit 1; fi
	$(CROSS)gcc $(FW_LINUX_FPGA_CFLAGS) -T $(FW_LINUX_FPGA_SRC)/link.ld -o $@ $(FW_LINUX_FPGA_SRC)/boot.S

$(FW_LINUX_FPGA_BIN): $(FW_LINUX_FPGA_ELF)
	$(CROSS)objcopy -O binary $< $@

$(FW_LINUX_FPGA_IMAGE): $(FW_LINUX_FPGA_BIN) $(FW_LINUX_FPGA_DTB) $(LINUX_FPGA_PAYLOAD)
	$(call _emit_fpga_image,$@,$(FW_LINUX_FPGA_BIN),$(LINUX_FPGA_PAYLOAD),$(LINUX_FPGA_DTB_OFFSET),$(LINUX_FPGA_DTB_SRC_ADDR),Linux FPGA)

$(FW_LINUX_FPGA_SMOKE_ELF): $(FW_LINUX_FPGA_SRC)/boot.S $(FW_LINUX_FPGA_SRC)/link.ld | $(FW_LINUX_FPGA_DIR)
	$(CROSS)gcc $(FW_LINUX_FPGA_SMOKE_CFLAGS) -T $(FW_LINUX_FPGA_SRC)/link.ld -o $@ $(FW_LINUX_FPGA_SRC)/boot.S

$(FW_LINUX_FPGA_SMOKE_BIN): $(FW_LINUX_FPGA_SMOKE_ELF)
	$(CROSS)objcopy -O binary $< $@

$(FW_LINUX_FPGA_SMOKE_IMAGE): $(FW_LINUX_FPGA_SMOKE_BIN)
	@cp $< $@
	@image_size=$$(stat -c%s "$@"); \
	 echo "[INFO] Linux FPGA smoke image: $@ ($$image_size bytes)"; \
	 echo "[INFO]   stage0-only diagnostic @ $(MAIN_RAM_BASE)"; \
	 echo "[INFO]   payload size=0, dtb size=0; expected to loop after jumping to $(MAIN_RAM_BASE)"

$(FW_LINUX_FPGA_OPENSBI_ELF): opensbi-build $(FW_LINUX_FPGA_SRC)/boot.S $(FW_LINUX_FPGA_SRC)/link.ld $(FW_LINUX_FPGA_DTB) $(LINUX_FPGA_OPENSBI_PAYLOAD) | $(FW_LINUX_FPGA_DIR)
	@if [ -z "$(LINUX_FPGA_OPENSBI_PAYLOAD)" ] || [ ! -f "$(LINUX_FPGA_OPENSBI_PAYLOAD)" ]; then \
		echo "[ERR] Linux FPGA OpenSBI payload not found after opensbi-build: $(LINUX_FPGA_OPENSBI_PAYLOAD)"; exit 1; fi
	$(CROSS)gcc $(FW_LINUX_FPGA_OPENSBI_CFLAGS) -T $(FW_LINUX_FPGA_SRC)/link.ld -o $@ $(FW_LINUX_FPGA_SRC)/boot.S

$(FW_LINUX_FPGA_OPENSBI_BIN): $(FW_LINUX_FPGA_OPENSBI_ELF)
	$(CROSS)objcopy -O binary $< $@

$(FW_LINUX_FPGA_OPENSBI_IMAGE): $(FW_LINUX_FPGA_OPENSBI_BIN) $(FW_LINUX_FPGA_DTB) $(LINUX_FPGA_OPENSBI_PAYLOAD)
	$(call _emit_fpga_image,$@,$(FW_LINUX_FPGA_OPENSBI_BIN),$(LINUX_FPGA_OPENSBI_PAYLOAD),$(LINUX_FPGA_OPENSBI_DTB_OFFSET),$(LINUX_FPGA_OPENSBI_DTB_SRC_ADDR),Linux FPGA OpenSBI)

sim-gen: $(PACK_SV) $(SIM_ROM_DEP) $(SIM_PAYLOAD_BUILD)
	@if [ "$(SIM_NEEDS_BIOS_PATCHES)" = "1" ]; then $(call _litex_bios_patches_apply); fi
	@trap '[ "$(SIM_NEEDS_BIOS_PATCHES)" = "1" ] && { $(call _litex_bios_patches_restore); } || true' EXIT; \
	$(call _soc_gen,$(SIM_FLAGS))

sim-build: sim-gen
	$(call _compile_if_needed,$(SIM_BUILD_DIR))

sim: sim-build
	$(call _run_vsim,$(SIM_BUILD_DIR))

sim-run:
	$(call _run_vsim,$(SIM_BUILD_DIR))

sim-trace:
	@$(call _make,sim TRACE=fst)

sim-trace-vcd:
	@$(call _make,sim TRACE=vcd)

coremark-build:
	$(MAKE) -C $(COREMARK_BENCH) build ITERATIONS=$(COREMARK_ITERATIONS) SYS_CLK_HZ=$(SYS_CLK)

coremark:
	@mkdir -p $(LITEX_LOG_DIR)
	@set -o pipefail; $(MAKE) --no-print-directory sim PAYLOAD=coremark \
		SIM_STOP_MARKER='CoreMark: done.' \
		SIM_TIMEOUT=$(if $(filter command line environment,$(origin SIM_TIMEOUT)),$(SIM_TIMEOUT),600) \
		COREMARK_ITERATIONS=$(COREMARK_ITERATIONS) \
		2>&1 | tee $(LITEX_LOG_DIR)/coremark.log

coremark-fpga: coremark-build
	@echo "[INFO] CoreMark built for SYS_CLK=$(SYS_CLK) Hz (VARIANT=$(VARIANT)) — the LOADED bitstream must run at this clock, else 'Total time'/'Iterations/Sec' are off by the clock ratio (rdtime timebase == sys_clk)."
	@$(call _make,fpga-upload BIN=$(COREMARK_BIN))

coremark-clean:
	$(MAKE) -C $(COREMARK_BENCH) clean

main-fpga-build:
	$(MAKE) -C $(LITEX_DIR) firmware-fpga FW_FPGA_TARGET=main FW_FPGA_LOAD=main_ram
	@echo "[INFO] FPGA main firmware ready: $(BUILD_DIR)/firmware/fpga/main-main_ram/boot.bin"

main-fpga: main-fpga-build
	@$(call _make,fpga-upload BIN=$(BUILD_DIR)/firmware/fpga/main-main_ram/boot.bin)

u-sv32-s-ecall-stress-fpga-build:
	$(MAKE) -C $(RAPTOR_HOME)/app/tests/irq $(ECALL_STRESS_FPGA_BIN) \
		BUILD_DIR=$(ECALL_STRESS_FPGA_DIR) EXTRA_CFLAGS=-DRAPT_LITEX_FPGA

u-sv32-s-ecall-stress-fpga-upload: u-sv32-s-ecall-stress-fpga-build
	@$(call _make,fpga-upload BIN=$(ECALL_STRESS_FPGA_BIN))

irqtest-fpga:
	$(MAKE) -C $(LITEX_DIR) firmware-fpga FW_FPGA_TARGET=irqtest FW_FPGA_LOAD=main_ram
	@$(call _make,fpga-upload BIN=$(BUILD_DIR)/firmware/fpga/irqtest-main_ram/boot.bin)

main-fpga-clean:
	rm -rf $(BUILD_DIR)/firmware/fpga/main-main_ram $(BUILD_DIR)/firmware/fpga/irqtest-main_ram

embench-build:
	$(MAKE) -C $(EMBENCH_BENCH) build SYS_CLK_HZ=$(SYS_CLK) \
		NETTLE_SHA256_LOCAL_SCALE=$(EMBENCH_NETTLE_SHA256_LOCAL_SCALE)

$(EMBENCH_BUILDS): embench-build-%:
	$(MAKE) -C $(EMBENCH_BENCH) build BENCH=$* SYS_CLK_HZ=$(SYS_CLK) \
		NETTLE_SHA256_LOCAL_SCALE=$(EMBENCH_NETTLE_SHA256_LOCAL_SCALE)

embench-build-one:
	$(call _require_var,BENCH,$(BENCH),Set BENCH=<name>)
	@$(call _make,embench-build-$(BENCH))

$(EMBENCH_TARGETS): embench-run-%:
	@$(call _make,sim PAYLOAD=embench-$*)

embench-run:
	$(call _require_var,BENCH,$(BENCH),Set BENCH=<name>)
	@$(call _make,sim PAYLOAD=embench-$(BENCH))

embench: $(PACK_SV) $(FW_SIM_BIN)
	@$(MAKE) --no-print-directory sim-build ROM=sim
	@mkdir -p $(EMBENCH_LOG_DIR)
	@set -o pipefail; env BENCHES="$(EMBENCH_RUN_BENCHES)" LOG_DIR=$(EMBENCH_LOG_DIR) ROM=sim \
		SYS_CLK_HZ=$(SYS_CLK) \
		SIM_TIMEOUT=$(if $(filter command line environment,$(origin SIM_TIMEOUT)),$(SIM_TIMEOUT),1200) \
		EMBENCH_NETTLE_SHA256_LOCAL_SCALE=$(EMBENCH_NETTLE_SHA256_LOCAL_SCALE) \
		$(if $(strip $(EMBENCH_JOBS)),JOBS=$(EMBENCH_JOBS),) \
		bash $(EMBENCH_BENCH)/run-embench.sh 2>&1 | tee $(LITEX_LOG_DIR)/embench.log

embench-report:
	@env $(if $(filter command line environment,$(origin EMBENCH_NETTLE_SHA256_LOCAL_SCALE)),EMBENCH_NETTLE_SHA256_LOCAL_SCALE=$(EMBENCH_NETTLE_SHA256_LOCAL_SCALE)) \
		bash $(EMBENCH_BENCH)/report-embench.sh $(EMBENCH_LOG_DIR)

embench-clean:
	$(MAKE) -C $(EMBENCH_BENCH) clean
	rm -rf $(EMBENCH_LOG_DIR)

app-llm-build:
	$(MAKE) -C $(APP_LLM_BENCH) litex-build $(APP_LLM_VARS)

$(APP_LLM_BUILDS): app-llm-build-%:
	$(MAKE) -C $(APP_LLM_BENCH) litex-build-one BENCH=$* $(APP_LLM_VARS)

$(APP_LLM_TARGETS): app-llm-%:
	@$(call _make,sim PAYLOAD=app-llm-$* $(APP_LLM_VARS))

app-llm-run:
	$(call _require_var,BENCH,$(BENCH),Set BENCH=ops|infer|train)
	@$(call _make,sim PAYLOAD=app-llm-$(BENCH) $(APP_LLM_VARS))

$(APP_LLM_FPGAS): app-llm-%-fpga: app-llm-build-%
	@$(call _make,fpga-upload BIN=$(APP_LLM_BUILD_DIR)/llm-$*.bin)

app-llm-fpga:
	$(call _require_var,BENCH,$(BENCH),Set BENCH=ops|infer|train)
	@$(call _make,app-llm-$(BENCH)-fpga $(APP_LLM_VARS))

app-fpga-upload:
	$(call _require_var,APP_FPGA_BIN,$(APP_FPGA_BIN),Set APP_FPGA_BIN=/path/to.bin)
	@$(call _make,fpga-upload BIN=$(APP_FPGA_BIN))

microbench-build:
	$(MAKE) -C $(MICROBENCH_DIR) ARCH=riscv32-npc

microbench:
	@mkdir -p $(LITEX_LOG_DIR)
	@set -o pipefail; $(MAKE) --no-print-directory sim PAYLOAD=microbench \
		2>&1 | tee $(LITEX_LOG_DIR)/microbench.log

tests:
	$(MAKE) -C $(TESTS_DIR) BUILD_DIR=$(TESTS_BUILD_DIR)

tests-clean:
	$(MAKE) -C $(TESTS_DIR) BUILD_DIR=$(TESTS_BUILD_DIR) clean

$(TEST_TARGETS): test-%:
	@$(call _make,sim PAYLOAD=test-$*)

tests-run: tests
	@mkdir -p $(LITEX_LOG_DIR)
	@{ set -e; for t in $(TEST_NAMES); do \
		echo "================================================================"; \
		echo "[tests-run] Running test-$$t"; \
		echo "================================================================"; \
		$(MAKE) --no-print-directory sim PAYLOAD=test-$$t SIM_TIMEOUT=$(SIM_TIMEOUT) || exit 1; \
	done; \
	echo "[tests-run] All tests completed."; } 2>&1 | tee $(LITEX_LOG_DIR)/tests-run.log

opensbi-build:
	$(MAKE) -C $(LINUX_DIR) opensbi

opensbi:
	@$(call _make,sim PAYLOAD=opensbi)

opensbi-clean:
	$(MAKE) -C $(LINUX_DIR) opensbi-clean

payload:
	$(call _require_var,IMG,$(IMG),Set IMG=/path/to/binary.bin)
	@$(call _make,sim PAYLOAD=img IMG=$(IMG))

egos-ku15p-sim: fpga-egos-prepare
	@echo "[INFO] Simulating egos-ku15p (Verilator LiteX SoC — same map as FPGA, zero-latency SRAM)."
	@echo "[INFO] If this runs fine but FPGA hangs → DDR4-latency or FPGA-specific RTL bug."
	@echo "[INFO] Use TRACE=fst to capture waveform: make egos-ku15p-sim TRACE=fst"
	@$(call _make,sim PAYLOAD=img IMG=$(EGOS_KU15P_BIN) SIM_TIMEOUT=$(SIM_TIMEOUT))

egos-ku15p-sim-trace: fpga-egos-prepare
	@$(call _make,egos-ku15p-sim TRACE=fst)

linux-build:
	$(MAKE) -s -C $(LINUX_DIR) download-rv32

linux:
	@$(call _make,sim PAYLOAD=linux VARIANT=linux)

linux-fpga-build:
	@$(call _make,fpga-build $(_LINUX_FPGA_ARGS))

linux-fpga-load:
	@$(call _make,fpga-load $(_LINUX_FPGA_ARGS))

linux-fpga-upload:
	@$(call _make,fpga-upload $(_LINUX_FPGA_ARGS))

linux-fpga-run:
	@$(call _make,fpga-load $(_LINUX_FPGA_ARGS))
	@$(call _make,linux-fpga-upload)

linux-fpga-e2e:
	@$(call _make,fpga-build $(_LINUX_FPGA_ARGS))
	@$(call _make,linux-fpga-run)

opensbi-fpga-upload:
	@$(call _make,fpga-opensbi-upload $(_LINUX_FPGA_ARGS))

opensbi-fpga-run:
	@$(call _make,fpga-load $(_LINUX_FPGA_ARGS))
	@$(call _make,opensbi-fpga-upload)

opensbi-fpga-e2e:
	@$(call _make,fpga-build $(_LINUX_FPGA_ARGS))
	@$(call _make,opensbi-fpga-run)

fpga-opensbi-upload: fpga-opensbi-img
	@$(call _fpga_linux_upload,$(FW_LINUX_FPGA_OPENSBI_IMAGE))

fpga-smoke-upload: fpga-smoke-img
	@$(call _fpga_linux_upload,$(FW_LINUX_FPGA_SMOKE_IMAGE))

fpga-smoke:
	@$(call _make,fpga $(_LINUX_FPGA_ARGS))
	@$(call _make,fpga-smoke-upload)

fpga-tinyos-prepare:
	@os="$(LINUX_FPGA_TINYOS_OS)"; \
	if [ -z "$$os" ]; then echo "[ERR] Set OS=egos|xv6 or TINYOS_OS=egos|xv6"; exit 1; fi; \
	case "$$os" in \
	  egos) $(MAKE) --no-print-directory fpga-egos-prepare ;; \
	  xv6)  $(MAKE) --no-print-directory fpga-xv6-prepare ;; \
	  *) echo "[ERR] Unsupported TinyOS OS '$$os' (use OS=egos or OS=xv6)"; exit 1 ;; \
	esac

fpga-egos-prepare:
	@echo "[INFO] Building egos-2000 KU15P RAM-disk image via app/tinyos"
	@$(MAKE) --no-print-directory -C $(RAPTOR_HOME)/app/tinyos egos-ku15p-image
	@test -f "$(LINUX_FPGA_EGOS_KU15P_IMAGE)" || { echo "[ERR] Missing egos KU15P image: $(LINUX_FPGA_EGOS_KU15P_IMAGE)"; exit 1; }
	@test -f "$(LINUX_FPGA_EGOS_IMAGE)" || { echo "[ERR] Missing egos kernel: $(LINUX_FPGA_EGOS_IMAGE)"; exit 1; }
	@test -f "$(LINUX_FPGA_EGOS_DISK)" || { echo "[ERR] Missing egos disk: $(LINUX_FPGA_EGOS_DISK)"; exit 1; }
	@echo "[INFO] egos kernel: $(LINUX_FPGA_EGOS_IMAGE)"
	@echo "[INFO] egos disk:   $(LINUX_FPGA_EGOS_DISK)"
	@echo "[INFO]   upload: make fpga-egos-upload   (forces VARIANT=linux; UART $(UART_PORT) @ linux-profile baud)"

fpga-egos-bundle: fpga-egos-prepare $(FW_EGOS_STAGE0_BIN)
	@stage_size=$$(stat -c%s "$(FW_EGOS_STAGE0_BIN)"); \
	 kernel_size=$$(stat -c%s "$(LINUX_FPGA_EGOS_IMAGE)"); \
	 disk_size=$$(stat -c%s "$(LINUX_FPGA_EGOS_DISK)"); \
	 if [ $$stage_size -gt $$((0x1000)) ]; then echo "[ERR] egos stage0 exceeds 4 KiB: $$stage_size"; exit 1; fi; \
	 if [ $$kernel_size -gt $$((0x10000)) ]; then echo "[ERR] egos kernel exceeds 64 KiB slot: $$kernel_size"; exit 1; fi; \
	 if [ $$disk_size -ne $$((0x400000)) ]; then echo "[ERR] egos disk must be exactly 4 MiB: $$disk_size"; exit 1; fi; \
	 cp "$(FW_EGOS_STAGE0_BIN)" "$(FW_EGOS_STAGE0_BUNDLE)"; \
	 truncate -s $$((0x1000)) "$(FW_EGOS_STAGE0_BUNDLE)"; \
	 cat "$(LINUX_FPGA_EGOS_IMAGE)" >> "$(FW_EGOS_STAGE0_BUNDLE)"; \
	 truncate -s $$((0x11000)) "$(FW_EGOS_STAGE0_BUNDLE)"; \
	 cat "$(LINUX_FPGA_EGOS_DISK)" >> "$(FW_EGOS_STAGE0_BUNDLE)"; \
	 bundle_size=$$(stat -c%s "$(FW_EGOS_STAGE0_BUNDLE)"); \
	 echo "[INFO] Compact egos bundle: $(FW_EGOS_STAGE0_BUNDLE) ($$bundle_size bytes)"; \
	 echo "[INFO]   stage0 @ $(LINUX_FPGA_EGOS_STAGE_ADDR), kernel -> 0x80000000, disk -> 0x80800000"

fpga-xv6-prepare:
	@echo "[INFO] Building xv6-riscv kernel.bin and fs.img via app/tinyos"
	@$(MAKE) --no-print-directory -C $(RAPTOR_HOME)/app/tinyos xv6-sim-image
	@test -f "$(LINUX_FPGA_XV6_KERNEL)" || { echo "[ERR] Missing xv6 kernel: $(LINUX_FPGA_XV6_KERNEL)"; exit 1; }
	@test -f "$(LINUX_FPGA_XV6_DISK)" || { echo "[ERR] Missing xv6 disk: $(LINUX_FPGA_XV6_DISK)"; exit 1; }
	@echo "[INFO] xv6 kernel: $(LINUX_FPGA_XV6_KERNEL)"
	@echo "[INFO] xv6 disk:   $(LINUX_FPGA_XV6_DISK)"

fpga-tinyos-check:
	@os="$(LINUX_FPGA_TINYOS_OS)"; \
	if [ -z "$$os" ]; then echo "[ERR] Set OS=egos|xv6 or TINYOS_OS=egos|xv6"; exit 1; fi; \
	case "$$os" in \
	  egos) \
		echo "[INFO] egos-2000 KU15P compact bundle is ready for serialboot upload."; \
		echo "      Bundle: $(FW_EGOS_STAGE0_BUNDLE)"; \
		echo "      Build: make fpga-egos-prepare"; \
		echo "      Upload: make fpga-egos-upload UART_PORT=$(UART_PORT) UART_BAUD=$(UART_BAUD)"; \
		echo "      Stage0 restores egos at 0x80000000 and disk.img at 0x80800000."; \
		;; \
	  xv6) \
		echo "[ERR] xv6-riscv artifacts are prepared, but they cannot run on the current KU15P Linux/MIG bitstream."; \
		echo "      Kernel: $(LINUX_FPGA_XV6_KERNEL)"; \
		echo "      Disk:   $(LINUX_FPGA_XV6_DISK)"; \
		echo "      Prepare/build command:"; \
		echo "        make fpga-xv6-prepare"; \
		echo "      Required before FPGA serialboot can be correct:"; \
		echo "        - RV64/Sv39 FPGA CPU/bitstream, not the current RV32 VARIANT=linux bitstream"; \
		echo "        - UART/CLINT/PLIC/virtio-blk map compatible with xv6, or an xv6 LiteX port"; \
		echo "        - $(LINUX_FPGA_XV6_DISK) exposed as the xv6 block device"; \
		echo "      Simulator validation command:"; \
		echo "        make -C $(RAPTOR_HOME)/app/tinyos xv6-cli-nsim ARGS='-b -n'"; \
		exit 2; \
		;; \
	  *) echo "[ERR] Unsupported TinyOS OS '$$os' (use OS=egos or OS=xv6)"; exit 1 ;; \
	esac

fpga-tinyos-upload:
	@os="$(LINUX_FPGA_TINYOS_OS)"; \
	if [ -z "$$os" ]; then echo "[ERR] Set OS=egos|xv6 or TINYOS_OS=egos|xv6"; exit 1; fi; \
	case "$$os" in \
	  egos) $(MAKE) --no-print-directory fpga-egos-upload ;; \
	  xv6)  $(MAKE) --no-print-directory fpga-xv6-upload ;; \
	  *) echo "[ERR] Unsupported TinyOS OS '$$os' (use OS=egos or OS=xv6)"; exit 1 ;; \
	esac

fpga-egos-upload: fpga-egos-bundle
	@$(MAKE) --no-print-directory fpga-upload $(_LINUX_FPGA_ARGS) \
		BIN=$(FW_EGOS_STAGE0_BUNDLE) MAIN_RAM_BASE=$(LINUX_FPGA_EGOS_STAGE_ADDR)

fpga-raptos-build:
	@$(MAKE) --no-print-directory -C $(RAPTOR_HOME)/app/tinyos/raptos all PLATFORM=ku15p

fpga-raptos-upload: fpga-raptos-build
	@$(MAKE) --no-print-directory fpga-upload $(_LINUX_FPGA_ARGS) \
		BIN=$(RAPTOS_KU15P_BIN) MAIN_RAM_BASE=$(MAIN_RAM_BASE)

fpga-raptos-run:
	@$(MAKE) --no-print-directory fpga-raptos-upload $(_LINUX_FPGA_ARGS)

fpga-xv6-upload: fpga-xv6-prepare
	@$(MAKE) --no-print-directory fpga-tinyos-check OS=xv6

bios:
	@$(MAKE) --no-print-directory sim ROM=bios SOC=$(SOC) PAYLOAD=$(PAYLOAD)

fpga-detect:
	@if [ -n "$(FPGA_DETECTED_BOARD)" ]; then \
		echo "[INFO] Detected FPGA_BOARD=$(FPGA_DETECTED_BOARD) (parts: $(FPGA_DETECTED_PARTS))"; \
	else \
		echo "[WARN] No supported Xilinx FPGA detected; default would be FPGA_BOARD=$(FPGA_BOARD)."; \
		echo "[WARN] Set FPGA_BOARD explicitly for Gowin or an unrecognized JTAG device."; \
	fi

fpga-gen: $(PACK_SV) $(_FPGA_FW_DEP)
	@$(call _run_litex_target,$(_FPGA_FLAGS) --build --no-compile-gateware)
	@echo "[INFO] Sources generated under $(FPGA_BUILD_DIR) (BOOT_MODE=$(BOOT_MODE))"

fpga-build: $(PACK_SV) $(_FPGA_FW_DEP)
	@echo "[INFO] FPGA board: $(FPGA_BOARD) (source=$(FPGA_BOARD_SOURCE), vendor=$(FPGA_VENDOR), device=$(if $(FPGA_DEVICE),$(FPGA_DEVICE),n/a))"
ifeq ($(FPGA_VENDOR),gowin)
	@if [ -z "$(strip $(GOWIN_APP))" ]; then \
		echo "[ERR] GOWIN_APP is empty — install GowinIDE.app or set GOWIN_APP=/path/to/GowinIDE.app"; exit 1; fi
	@if [ ! -x "$(GOWIN_BIN_DIR)/gw_sh" ]; then \
		echo "[ERR] gw_sh not found at $(GOWIN_BIN_DIR)/gw_sh"; exit 1; fi
else
	@command -v $(VIVADO) >/dev/null 2>&1 || { \
		echo "[ERR] $(VIVADO) not found on PATH — source the Vivado settings64.sh first"; exit 1; }
endif
	@mkdir -p $(FPGA_DIR)
	@OLD_HASH=$$(cat $(FPGA_STAMP) 2>/dev/null || echo ""); \
	NEW_HASH="$(_FPGA_HASH_KEY)"; \
	if [ -f "$(FPGA_BITSTREAM)" ] && [ "$$OLD_HASH" = "$$NEW_HASH" ]; then \
		echo "[INFO] Bitstream up to date (BOOT_MODE=$(BOOT_MODE), hash=$${NEW_HASH:0:12})"; \
		echo "[INFO]   $(FPGA_BITSTREAM)"; \
		echo "[INFO] Force rebuild with: make fpga-build-force"; \
		$(MAKE) --no-print-directory fpga-reports-index $(_FPGA_REPORTS_INDEX_ARGS); \
		exit 0; \
	fi; \
	echo "[INFO] Bitstream stale (old=$${OLD_HASH:0:12} new=$${NEW_HASH:0:12}); running $(FPGA_VENDOR)..."; \
	if [ "$(FPGA_VENDOR)" = "vivado" ]; then \
		$(VIVADO) -mode batch -nojournal -nolog -notrace \
			-source $(LITEX_DIR)/scripts/vivado_check_part.tcl -tclargs $(FPGA_PART) || exit 1; \
	fi; \
	$(call _run_litex_target,$(_FPGA_FLAGS) --build) && \
	printf '%s' "$$NEW_HASH" > $(FPGA_STAMP)
	@$(MAKE) --no-print-directory fpga-reports-index $(_FPGA_REPORTS_INDEX_ARGS)
	@echo ""
	@echo "========================================="
	@echo " Bitstream ready: $(FPGA_BITSTREAM)"
	@echo " Load (volatile):  make fpga-load"
	@if [ "$(FPGA_VENDOR)" != "vivado" ] || [ "$(BOARD_$(FPGA_BOARD)_VIVADO_FLASH)" = "1" ]; then \
		echo " Flash (persist):  make fpga-flash"; \
	else \
		echo " Flash (persist):  unsupported for $(FPGA_BOARD)"; \
	fi
	@if [ "$(FPGA_VENDOR)" = "gowin" ]; then \
		echo " Reports index:    $(GOWIN_REPORTS_INDEX_DST)"; \
	else \
		echo " Reports index:    $(VIVADO_REPORTS_INDEX_DST)"; \
	fi
	@echo "========================================="
ifeq ($(LINUX_FPGA_PROFILE),1)
	@$(MAKE) --no-print-directory fpga-timing-ok
endif

fpga-reports-index:
ifeq ($(FPGA_VENDOR),gowin)
	@if [ -d "$(FPGA_BUILD_DIR)/impl" ]; then \
		cp $(GOWIN_REPORTS_INDEX_SRC) $(GOWIN_REPORTS_INDEX_DST); \
		echo "[INFO] Reports index: $(GOWIN_REPORTS_INDEX_DST)"; \
	else \
		echo "[WARN] $(FPGA_BUILD_DIR)/impl not found — run 'make fpga-build' first."; \
	fi
else
	@if [ -d "$(FPGA_BUILD_DIR)" ]; then \
		if ls "$(FPGA_BUILD_DIR)"/*.rpt >/dev/null 2>&1; then \
			$(HOST_PYTHON) $(VIVADO_REPORTS_INDEX_GEN) $(FPGA_BUILD_DIR) \
				--output $(VIVADO_REPORTS_INDEX_DST) \
				--title "Vivado Reports - $(FPGA_BOARD) $(BOOT_MODE) $(RAPT_CONFIG)"; \
		else \
			echo "[WARN] no Vivado .rpt files under $(FPGA_BUILD_DIR) — run 'make fpga-build' first."; \
		fi; \
	else \
		echo "[WARN] $(FPGA_BUILD_DIR) not found — run 'make fpga-build' first."; \
	fi
endif

fpga-timing-ok:
ifeq ($(FPGA_VENDOR),vivado)
	@rpt="$(FPGA_BUILD_DIR)/$(FPGA_TIMINGRPT)"; \
	if [ ! -f "$$rpt" ]; then \
		echo "[ERR] Vivado timing report not found: $$rpt"; \
		echo "[ERR] Run 'make fpga-build' first."; \
		exit 1; \
	fi; \
	if grep -q "Timing constraints are not met" "$$rpt"; then \
		echo "[ERR] Vivado timing constraints are not met; refusing hardware load/flash/upload."; \
		echo "[ERR] Report: $$rpt"; \
		awk '/Design Timing Summary/{show=1} show && /Timing constraints are not met/{print; exit} show{print}' "$$rpt" | sed -n '1,18p'; \
		exit 1; \
	fi; \
	if grep -Eiq "Timing constraints are met|All user specified timing constraints are met" "$$rpt"; then \
		echo "[INFO] Vivado timing constraints are met: $$rpt"; \
	else \
		echo "[ERR] Could not determine Vivado timing status from: $$rpt"; \
		exit 1; \
	fi
else
	@echo "[INFO] Timing gate not implemented for FPGA_VENDOR=$(FPGA_VENDOR); skipping."
endif

fpga-build-force:
	@rm -f $(FPGA_STAMP)
	@$(call _make,fpga-build)

fpga-bitstream-current:
	@OLD_HASH=$$(cat $(FPGA_STAMP) 2>/dev/null || echo ""); \
	NEW_HASH="$(_FPGA_HASH_KEY)"; \
	if [ -z "$$OLD_HASH" ] || [ "$$OLD_HASH" != "$$NEW_HASH" ]; then \
		echo "[ERR] Refusing to program a stale or untracked bitstream."; \
		echo "[ERR] Bitstream stamp: $${OLD_HASH:-missing}"; \
		echo "[ERR] Current input hash: $$NEW_HASH"; \
		echo "[ERR] Run 'make fpga-build' with the same FPGA_BOARD, VARIANT, BOOT_MODE, and RAPT_CONFIG."; \
		exit 1; \
	fi

fpga-load: fpga-bitstream-current
	@echo "[INFO] FPGA board: $(FPGA_BOARD) (source=$(FPGA_BOARD_SOURCE), vendor=$(FPGA_VENDOR), device=$(if $(FPGA_DEVICE),$(FPGA_DEVICE),n/a))"
	$(call _require_file,$(FPGA_BITSTREAM),$(FPGA_BITSTREAM) not found — run 'make fpga-build' first.)
	@$(FPGA_LOAD_TOOL_CHECK)
	$(FPGA_LOAD_CMD)

fpga-flash: fpga-bitstream-current
	$(call _require_file,$(FPGA_BITSTREAM),$(FPGA_BITSTREAM) not found — run 'make fpga-build' first.)
	@if [ "$(FPGA_VENDOR)" = "vivado" ] && [ "$(BOARD_$(FPGA_BOARD)_VIVADO_FLASH)" != "1" ]; then \
		echo "[ERR] Persistent flash is not configured for FPGA_BOARD=$(FPGA_BOARD); refusing to use a board-specific cfgmem script."; \
		exit 1; \
	fi
	@$(FPGA_LOAD_TOOL_CHECK)
	$(FPGA_FLASH_CMD)

mlk-cu07-ku15p:
	@$(call _make,fpga FPGA_BOARD=mlk_cu07_ku15p)

mlk-cu07-ku15p-build:
	@$(call _make,fpga-build FPGA_BOARD=mlk_cu07_ku15p)

xilinx-vcu118:
	@$(call _make,fpga FPGA_BOARD=xilinx_vcu118)

xilinx-vcu118-build:
	@$(call _make,fpga-build FPGA_BOARD=xilinx_vcu118)

fpga-console:
	$(call _require_var,UART_PORT,$(UART_PORT),UART_PORT empty — plug in the board or set UART_PORT=/dev/tty.usbserial-XXXX)
	@echo "[INFO] Opening $(UART_PORT) @ $(UART_BAUD) baud (Ctrl-A K = quit)"
	source $(VENV_DIR)/bin/activate && \
	litex_term --speed=$(UART_BAUD) $(UART_PORT)

fpga-upload: $(_FPGA_UPLOAD_DEPS)
	$(call _require_var,UART_PORT,$(UART_PORT),UART_PORT empty — set UART_PORT=/dev/tty.usbserial-XXXX)
	@bin="$(BIN)"; [ -z "$$bin" ] && bin="$(_FPGA_UPLOAD_DEFAULT_BIN)"; \
	if [ ! -f "$$bin" ]; then \
		echo "[ERR] $$bin not found — build it first (e.g. 'make firmware-fpga FW_FPGA_TARGET=$(FW_FPGA_TARGET) FW_FPGA_LOAD=main_ram')"; exit 1; fi; \
	echo "[INFO] Uploading $$bin to MAIN_RAM ($(MAIN_RAM_BASE)) via BIOS serialboot on $(UART_PORT)"; \
	if [ -n "$(SERIALBOOT_SAFE_FLAG)" ]; then echo "[INFO] Using litex_term --safe (SERIALBOOT_SAFE=$(SERIALBOOT_SAFE))"; fi; \
	echo "[INFO] Power-cycle / press the reboot button on the board if the BIOS prompt has timed out."; \
	source $(VENV_DIR)/bin/activate && \
	litex_term --speed=$(UART_BAUD) $(SERIALBOOT_SAFE_FLAG) --kernel="$$bin" --kernel-adr=$(MAIN_RAM_BASE) $(UART_PORT)

fpga-clean:
	rm -rf $(FPGA_DIR)

clean:
	rm -rf $(BUILD_DIR)
	@echo "Build artifacts cleaned."

sim-clean:
	@rm -rf $(BUILD_DIR)/sim
	@echo "Verilator binary + hash cache cleared (all VARIANT-ROM-SOC combinations)."

clean-all: clean firmware-clean
	rm -rf $(VENV_DIR)
	@echo "Virtual environment removed."

lint:
	$(MAKE) -C $(RAPTOR_HOME) lint

info:
	@$(foreach v,$(_INFO_VARS),echo "$v = $($v)";)
	@echo "---- sim ----"
	@echo "ROM          = $(ROM)"
	@echo "SOC          = $(SOC)"
	@echo "PAYLOAD      = $(PAYLOAD)"
	@echo "SIM_DIR      = $(SIM_DIR)"
	@echo "SIM_BUILD_DIR   = $(SIM_BUILD_DIR)"
	@echo "VSIM         = $(SIM_BUILD_DIR)/obj_dir/Vsim (exists: $(shell test -f $(SIM_BUILD_DIR)/obj_dir/Vsim && echo yes || echo no))"
	@echo "---- fpga ----"
	@echo "FPGA_BOARD   = $(FPGA_BOARD)"
	@echo "FPGA_DIR     = $(FPGA_DIR)"
	@echo "FPGA_BITSTRM = $(FPGA_BITSTREAM) (exists: $(shell test -f $(FPGA_BITSTREAM) && echo yes || echo no))"
	@echo "BOOT_MODE    = $(BOOT_MODE)"
	@echo "FPGA_STAMP   = $(FPGA_STAMP) (cached: $(shell test -f $(FPGA_STAMP) && echo yes || echo no))"
	@echo "---- linux fpga profile ----"
	@echo "LINUX_FPGA_PROFILE = $(LINUX_FPGA_PROFILE)"
	@echo "LINUX_FPGA_RAM_SIZE= $(LINUX_FPGA_RAM_SIZE)"
	@echo "LINUX_FPGA_PAYLOAD = $(LINUX_FPGA_PAYLOAD)"
	@echo "LINUX_FPGA_IMAGE   = $(FW_LINUX_FPGA_IMAGE) (exists: $(shell test -f $(FW_LINUX_FPGA_IMAGE) && echo yes || echo no))"

help:
	@awk -v guide="$(LITEX_DIR)/README.md" -f $(LITEX_DIR)/scripts/make_help.awk $(MAKEFILE_LIST)

