#!/usr/bin/env python3
"""Generate a hand-written behavioral Liberty .lib and a synthesizable .v
for a raptor-chip 1R1W cache SRAM macro.

This is a *placeholder* for OpenRAM output. It lets `make sta-sram` close
the loop (Yosys keeps the macro as a black box; OpenSTA reads timing from
the .lib) without requiring a full PDK / OpenRAM install. The numbers are
deliberately conservative single-cycle access models; replace with the
real OpenRAM-generated artefacts (`make sram-macros`) before quoting
silicon-grade timing.

Usage:
  gen_stub_lib.py <macro_name> <depth> <data_width> <write_size> <outdir>

All macros are single-port (1RW): one shared read/write port.

Outputs:
  <outdir>/<macro_name>.lib
  <outdir>/<macro_name>.v
"""
from __future__ import annotations

import math
import os
import sys
import textwrap


def addr_width(depth: int) -> int:
    return max(1, math.ceil(math.log2(depth)))


def emit_lib(name: str, depth: int, width: int, write_size: int) -> str:
    aw = addr_width(depth)
    bytes_ = width // write_size
    # Rough per-bit area for an sky130-class HD 6T bitcell + periphery.
    # 1 bit ~= 2.0 um^2 (cell), +10% for the single-port decoder/drivers/io
    # set. Liberty area unit defaults to 1 (technology dependent).
    area = round(depth * width * 2.0 * 1.1, 2)
    # Single-cycle access: data is captured at clk edge, output valid at
    # next edge. Use 0.4 ns setup, 0.15 ns hold, 0.8 ns clk->Q.
    setup = 0.4
    hold = 0.15
    ck_q = 0.8
    cap_in = 0.005   # pF
    cap_clk = 0.020  # pF
    ports_desc = "1 shared read/write port"

    # Single-port macro: data-out bus with its clk->Q arc on port 0.
    dout0_arc = f"""
        bus (dout0) {{
          bus_type : data0_bus_t;
          direction : output;
          max_capacitance : 0.5;
          pin (dout0[{width - 1}:0]) {{
            timing () {{
              related_pin : clk0;
              timing_type : rising_edge;
              timing_sense : non_unate;
              cell_rise (delay_template) {{
                values ("{ck_q}, {ck_q + 0.2}", "{ck_q + 0.2}, {ck_q + 0.4}");
              }}
              cell_fall (delay_template) {{
                values ("{ck_q}, {ck_q + 0.2}", "{ck_q + 0.2}, {ck_q + 0.4}");
              }}
              rise_transition (delay_template) {{
                values ("0.1, 0.2", "0.2, 0.3");
              }}
              fall_transition (delay_template) {{
                values ("0.1, 0.2", "0.2, 0.3");
              }}
            }}
          }}
        }}
"""

    header = textwrap.dedent(f"""\
    /* ------------------------------------------------------------------
     * Behavioral Liberty stub for {name}
     *   shape       : {depth} words x {width} bits ({depth * width // 8} B)
     *   write_size  : {write_size} bits (byte enables = {bytes_})
     *   ports       : {ports_desc}
     *   model       : placeholder for OpenRAM output. NOT silicon-grade.
    * Generated by sim/sram/scripts/gen_stub_lib.py
     * ------------------------------------------------------------------ */

    library ({name}) {{
      delay_model              : table_lookup;
      time_unit                : "1ns";
      voltage_unit             : "1V";
      current_unit             : "1mA";
      capacitive_load_unit      (1, pf);
      pulling_resistance_unit  : "1kohm";
      leakage_power_unit       : "1nW";

      default_max_transition   : 0.5;
      default_max_fanout       : 16;
      default_cell_leakage_power : 0;
      default_fanout_load      : 1;
      default_inout_pin_cap    : {cap_in};
      default_input_pin_cap    : {cap_in};
      default_output_pin_cap   : 0;
      default_max_capacitance  : 0.5;

      nom_voltage              : 1.8;
      nom_temperature          : 25.0;
      nom_process              : 1.0;

      operating_conditions ("typ") {{
        process     : 1.0;
        voltage     : 1.8;
        temperature : 25.0;
      }}
      default_operating_conditions : "typ";

      lu_table_template (delay_template) {{
        variable_1 : input_net_transition;
        variable_2 : total_output_net_capacitance;
        index_1    ("0.05, 0.5");
        index_2    ("0.005, 0.05");
      }}

      cell ({name}) {{
        area : {area};
        dont_use : false;
        dont_touch : true;
        is_macro_cell : true;
        interface_timing : true;

        /* ---------- Port 0: read/write ---------- */
        pin (clk0) {{
          direction : input;
          clock : true;
          capacitance : {cap_clk};
          min_period : 1.5;
        }}
        pin (csb0) {{
          direction : input;
          capacitance : {cap_in};
          timing () {{
            related_pin : clk0;
            timing_type : setup_rising;
            rise_constraint (scalar) {{ values ("{setup}"); }}
            fall_constraint (scalar) {{ values ("{setup}"); }}
          }}
          timing () {{
            related_pin : clk0;
            timing_type : hold_rising;
            rise_constraint (scalar) {{ values ("{hold}"); }}
            fall_constraint (scalar) {{ values ("{hold}"); }}
          }}
        }}
        pin (web0) {{
          direction : input;
          capacitance : {cap_in};
          timing () {{
            related_pin : clk0;
            timing_type : setup_rising;
            rise_constraint (scalar) {{ values ("{setup}"); }}
            fall_constraint (scalar) {{ values ("{setup}"); }}
          }}
          timing () {{
            related_pin : clk0;
            timing_type : hold_rising;
            rise_constraint (scalar) {{ values ("{hold}"); }}
            fall_constraint (scalar) {{ values ("{hold}"); }}
          }}
        }}
        bus (wmask0) {{
          bus_type : wmask0_bus_t;
          direction : input;
          capacitance : {cap_in};
          pin (wmask0[{bytes_ - 1}:0]) {{
            timing () {{
              related_pin : clk0;
              timing_type : setup_rising;
              rise_constraint (scalar) {{ values ("{setup}"); }}
              fall_constraint (scalar) {{ values ("{setup}"); }}
            }}
            timing () {{
              related_pin : clk0;
              timing_type : hold_rising;
              rise_constraint (scalar) {{ values ("{hold}"); }}
              fall_constraint (scalar) {{ values ("{hold}"); }}
            }}
          }}
        }}
        bus (addr0) {{
          bus_type : addr0_bus_t;
          direction : input;
          capacitance : {cap_in};
          pin (addr0[{aw - 1}:0]) {{
            timing () {{
              related_pin : clk0;
              timing_type : setup_rising;
              rise_constraint (scalar) {{ values ("{setup}"); }}
              fall_constraint (scalar) {{ values ("{setup}"); }}
            }}
            timing () {{
              related_pin : clk0;
              timing_type : hold_rising;
              rise_constraint (scalar) {{ values ("{hold}"); }}
              fall_constraint (scalar) {{ values ("{hold}"); }}
            }}
          }}
        }}
        bus (din0) {{
          bus_type : data0_bus_t;
          direction : input;
          capacitance : {cap_in};
          pin (din0[{width - 1}:0]) {{
            timing () {{
              related_pin : clk0;
              timing_type : setup_rising;
              rise_constraint (scalar) {{ values ("{setup}"); }}
              fall_constraint (scalar) {{ values ("{setup}"); }}
            }}
            timing () {{
              related_pin : clk0;
              timing_type : hold_rising;
              rise_constraint (scalar) {{ values ("{hold}"); }}
              fall_constraint (scalar) {{ values ("{hold}"); }}
            }}
          }}
        }}
        {dout0_arc}
      }}

      type (wmask0_bus_t) {{
        base_type : array;
        data_type : bit;
        bit_width : {bytes_};
        bit_from  : {bytes_ - 1};
        bit_to    : 0;
        downto    : true;
      }}
      type (addr0_bus_t) {{
        base_type : array;
        data_type : bit;
        bit_width : {aw};
        bit_from  : {aw - 1};
        bit_to    : 0;
        downto    : true;
      }}
      type (data0_bus_t) {{
        base_type : array;
        data_type : bit;
        bit_width : {width};
        bit_from  : {width - 1};
        bit_to    : 0;
        downto    : true;
      }}
    }}
    """)
    return header


def emit_v(name: str, depth: int, width: int, write_size: int) -> str:
    aw = addr_width(depth)
    bytes_ = width // write_size
    # Single shared read/write port: web0 low = write, high = read.
    # Read data is registered (OpenRAM single-port convention).
    return textwrap.dedent(f"""\
    // Behavioral model for {name} (stub for OpenRAM-compiled macro).
    // Functional only; not a synthesis target. Yosys reads this only to
    // satisfy module resolution when the blackbox attribute is dropped.

    module {name} (
        input  wire                  clk0,
        input  wire                  csb0,
        input  wire                  web0,
        input  wire [{bytes_ - 1}:0] wmask0,
        input  wire [{aw - 1}:0]     addr0,
        input  wire [{width - 1}:0]  din0,
        output reg  [{width - 1}:0]  dout0
    );
        reg [{width - 1}:0] mem [0:{depth - 1}];
        integer b;
        always @(posedge clk0) begin
            if (!csb0 && !web0) begin
                for (b = 0; b < {bytes_}; b = b + 1) begin
                    if (wmask0[b])
                        mem[addr0][b*{write_size} +: {write_size}] <=
                            din0[b*{write_size} +: {write_size}];
                end
            end else if (!csb0) begin
                dout0 <= mem[addr0];
            end
        end
    endmodule
    """)


def main(argv: list[str]) -> int:
    if len(argv) != 6:
        sys.stderr.write(__doc__)
        return 2
    name = argv[1]
    depth = int(argv[2])
    width = int(argv[3])
    write_size = int(argv[4])
    outdir = argv[5]
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f"{name}.lib"), "w") as f:
        f.write(emit_lib(name, depth, width, write_size))
    with open(os.path.join(outdir, f"{name}.v"), "w") as f:
        f.write(emit_v(name, depth, width, write_size))
    print(f"  generated {outdir}/{name}.lib  {outdir}/{name}.v")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
