// OSCPU/ysyxSoC ysyx6 CPU boundary. The SoC source remains unmodified.
// This adapter uses RV32; RV64 remains available through the standalone sim.
`include "rapt.svh"
`ifdef RAPT_YSYXSOC
module wrap_ysyxsoc (
    input logic        clock,
    input logic        reset,
    input logic        io_interrupt,
    input logic        io_master_awready,
    output logic        io_slave_awready,
    output logic        io_master_awvalid,
    input logic        io_slave_awvalid,
    output logic [31:0] io_master_awaddr,
    input logic [31:0] io_slave_awaddr,
    output logic [3:0]  io_master_awid,
    input logic [3:0]  io_slave_awid,
    output logic [7:0]  io_master_awlen,
    input logic [7:0]  io_slave_awlen,
    output logic [2:0]  io_master_awsize,
    input logic [2:0]  io_slave_awsize,
    output logic [1:0]  io_master_awburst,
    input logic [1:0]  io_slave_awburst,
    input logic        io_master_wready,
    output logic        io_slave_wready,
    output logic        io_master_wvalid,
    input logic        io_slave_wvalid,
    output logic [31:0] io_master_wdata,
    input logic [31:0] io_slave_wdata,
    output logic [3:0]  io_master_wstrb,
    input logic [3:0]  io_slave_wstrb,
    output logic        io_master_wlast,
    input logic        io_slave_wlast,
    output logic        io_master_bready,
    input logic        io_slave_bready,
    input logic        io_master_bvalid,
    output logic        io_slave_bvalid,
    input logic [1:0]  io_master_bresp,
    output logic [1:0]  io_slave_bresp,
    input logic [3:0]  io_master_bid,
    output logic [3:0]  io_slave_bid,
    input logic        io_master_arready,
    output logic        io_slave_arready,
    output logic        io_master_arvalid,
    input logic        io_slave_arvalid,
    output logic [31:0] io_master_araddr,
    input logic [31:0] io_slave_araddr,
    output logic [3:0]  io_master_arid,
    input logic [3:0]  io_slave_arid,
    output logic [7:0]  io_master_arlen,
    input logic [7:0]  io_slave_arlen,
    output logic [2:0]  io_master_arsize,
    input logic [2:0]  io_slave_arsize,
    output logic [1:0]  io_master_arburst,
    input logic [1:0]  io_slave_arburst,
    output logic        io_master_rready,
    input logic        io_slave_rready,
    input logic        io_master_rvalid,
    output logic        io_slave_rvalid,
    input logic [1:0]  io_master_rresp,
    output logic [1:0]  io_slave_rresp,
    input logic [31:0] io_master_rdata,
    output logic [31:0] io_slave_rdata,
    input logic        io_master_rlast,
    output logic        io_slave_rlast,
    input logic [3:0]  io_master_rid,
    output logic [3:0]  io_slave_rid
);
  initial begin
    if (`RAPT_XLEN != 32) $fatal(1, "ysyxSoC wrapper requires an RV32 build");
`ifdef RAPT_L2_EN
    $fatal(1, "ysyxSoC adapter does not yet support L2 burst refills");
`endif
  end
  // The upstream CPU slave port is reserved/unused. It does not expose RAM,
  // debug or DMA access; no requests are accepted and no response is fabricated.
  assign io_slave_awready = '0;
  assign io_slave_wready = '0;
  assign io_slave_bvalid = '0;
  assign io_slave_bresp = '0;
  assign io_slave_bid = '0;
  assign io_slave_arready = '0;
  assign io_slave_rvalid = '0;
  assign io_slave_rresp = '0;
  assign io_slave_rdata = '0;
  assign io_slave_rlast = '0;
  assign io_slave_rid = '0;

  // The upstream interface has no AxCACHE or JTAG pins. Normal/Device
  // classification is still enforced inside Raptor. Park the debug TAP.
  rapt #(
      .XLEN(32),
      .MemoryReadCredits(1)
  ) cpu (
      .clock(clock),
      .reset(reset),
      .io_interrupt(io_interrupt),
      .external_write_valid_i(1'b0),
      .external_write_pending_i(1'b0),
      .external_write_first_i(32'b0),
      .external_write_last_i(32'b0),
      .ext_irq_i('0),
      .jtag_trst_n(1'b0),
      .jtag_tms(1'b1),
      .jtag_tdi(1'b0),
      .jtag_tdo(),
      .io_master_arcache(),
      .io_master_awcache(),
      .io_master_awready(io_master_awready),
      .io_master_awvalid(io_master_awvalid),
      .io_master_awaddr(io_master_awaddr),
      .io_master_awid(io_master_awid),
      .io_master_awlen(io_master_awlen),
      .io_master_awsize(io_master_awsize),
      .io_master_awburst(io_master_awburst),
      .io_master_wready(io_master_wready),
      .io_master_wvalid(io_master_wvalid),
      .io_master_wdata(io_master_wdata),
      .io_master_wstrb(io_master_wstrb),
      .io_master_wlast(io_master_wlast),
      .io_master_bready(io_master_bready),
      .io_master_bvalid(io_master_bvalid),
      .io_master_bresp(io_master_bresp),
      .io_master_bid(io_master_bid),
      .io_master_arready(io_master_arready),
      .io_master_arvalid(io_master_arvalid),
      .io_master_araddr(io_master_araddr),
      .io_master_arid(io_master_arid),
      .io_master_arlen(io_master_arlen),
      .io_master_arsize(io_master_arsize),
      .io_master_arburst(io_master_arburst),
      .io_master_rready(io_master_rready),
      .io_master_rvalid(io_master_rvalid),
      .io_master_rresp(io_master_rresp),
      .io_master_rdata(io_master_rdata),
      .io_master_rlast(io_master_rlast),
      .io_master_rid(io_master_rid)
  );
endmodule

// Match the unmodified upstream BlackBox name. Tapeout delivery must rename
// this module and all internal modules to the assigned student ID namespace.
module ysyx_00000000 (
    input logic        clock,
    input logic        reset,
    input logic        io_interrupt,
    input logic        io_master_awready,
    output logic        io_slave_awready,
    output logic        io_master_awvalid,
    input logic        io_slave_awvalid,
    output logic [31:0] io_master_awaddr,
    input logic [31:0] io_slave_awaddr,
    output logic [3:0]  io_master_awid,
    input logic [3:0]  io_slave_awid,
    output logic [7:0]  io_master_awlen,
    input logic [7:0]  io_slave_awlen,
    output logic [2:0]  io_master_awsize,
    input logic [2:0]  io_slave_awsize,
    output logic [1:0]  io_master_awburst,
    input logic [1:0]  io_slave_awburst,
    input logic        io_master_wready,
    output logic        io_slave_wready,
    output logic        io_master_wvalid,
    input logic        io_slave_wvalid,
    output logic [31:0] io_master_wdata,
    input logic [31:0] io_slave_wdata,
    output logic [3:0]  io_master_wstrb,
    input logic [3:0]  io_slave_wstrb,
    output logic        io_master_wlast,
    input logic        io_slave_wlast,
    output logic        io_master_bready,
    input logic        io_slave_bready,
    input logic        io_master_bvalid,
    output logic        io_slave_bvalid,
    input logic [1:0]  io_master_bresp,
    output logic [1:0]  io_slave_bresp,
    input logic [3:0]  io_master_bid,
    output logic [3:0]  io_slave_bid,
    input logic        io_master_arready,
    output logic        io_slave_arready,
    output logic        io_master_arvalid,
    input logic        io_slave_arvalid,
    output logic [31:0] io_master_araddr,
    input logic [31:0] io_slave_araddr,
    output logic [3:0]  io_master_arid,
    input logic [3:0]  io_slave_arid,
    output logic [7:0]  io_master_arlen,
    input logic [7:0]  io_slave_arlen,
    output logic [2:0]  io_master_arsize,
    input logic [2:0]  io_slave_arsize,
    output logic [1:0]  io_master_arburst,
    input logic [1:0]  io_slave_arburst,
    output logic        io_master_rready,
    input logic        io_slave_rready,
    input logic        io_master_rvalid,
    output logic        io_slave_rvalid,
    input logic [1:0]  io_master_rresp,
    output logic [1:0]  io_slave_rresp,
    input logic [31:0] io_master_rdata,
    output logic [31:0] io_slave_rdata,
    input logic        io_master_rlast,
    output logic        io_slave_rlast,
    input logic [3:0]  io_master_rid,
    output logic [3:0]  io_slave_rid
);
  wrap_ysyxsoc adapter (
      .clock(clock),
      .reset(reset),
      .io_interrupt(io_interrupt),
      .io_master_awready(io_master_awready),
      .io_slave_awready(io_slave_awready),
      .io_master_awvalid(io_master_awvalid),
      .io_slave_awvalid(io_slave_awvalid),
      .io_master_awaddr(io_master_awaddr),
      .io_slave_awaddr(io_slave_awaddr),
      .io_master_awid(io_master_awid),
      .io_slave_awid(io_slave_awid),
      .io_master_awlen(io_master_awlen),
      .io_slave_awlen(io_slave_awlen),
      .io_master_awsize(io_master_awsize),
      .io_slave_awsize(io_slave_awsize),
      .io_master_awburst(io_master_awburst),
      .io_slave_awburst(io_slave_awburst),
      .io_master_wready(io_master_wready),
      .io_slave_wready(io_slave_wready),
      .io_master_wvalid(io_master_wvalid),
      .io_slave_wvalid(io_slave_wvalid),
      .io_master_wdata(io_master_wdata),
      .io_slave_wdata(io_slave_wdata),
      .io_master_wstrb(io_master_wstrb),
      .io_slave_wstrb(io_slave_wstrb),
      .io_master_wlast(io_master_wlast),
      .io_slave_wlast(io_slave_wlast),
      .io_master_bready(io_master_bready),
      .io_slave_bready(io_slave_bready),
      .io_master_bvalid(io_master_bvalid),
      .io_slave_bvalid(io_slave_bvalid),
      .io_master_bresp(io_master_bresp),
      .io_slave_bresp(io_slave_bresp),
      .io_master_bid(io_master_bid),
      .io_slave_bid(io_slave_bid),
      .io_master_arready(io_master_arready),
      .io_slave_arready(io_slave_arready),
      .io_master_arvalid(io_master_arvalid),
      .io_slave_arvalid(io_slave_arvalid),
      .io_master_araddr(io_master_araddr),
      .io_slave_araddr(io_slave_araddr),
      .io_master_arid(io_master_arid),
      .io_slave_arid(io_slave_arid),
      .io_master_arlen(io_master_arlen),
      .io_slave_arlen(io_slave_arlen),
      .io_master_arsize(io_master_arsize),
      .io_slave_arsize(io_slave_arsize),
      .io_master_arburst(io_master_arburst),
      .io_slave_arburst(io_slave_arburst),
      .io_master_rready(io_master_rready),
      .io_slave_rready(io_slave_rready),
      .io_master_rvalid(io_master_rvalid),
      .io_slave_rvalid(io_slave_rvalid),
      .io_master_rresp(io_master_rresp),
      .io_slave_rresp(io_slave_rresp),
      .io_master_rdata(io_master_rdata),
      .io_slave_rdata(io_slave_rdata),
      .io_master_rlast(io_master_rlast),
      .io_slave_rlast(io_slave_rlast),
      .io_master_rid(io_master_rid),
      .io_slave_rid(io_slave_rid)
  );
endmodule
`endif
