#!/usr/bin/env python3
"""Generate concrete baseline V encoding witnesses from vendored rv_v."""
import argparse
import hashlib
from pathlib import Path

HERE=Path(__file__).resolve().parent
FIELDS={'nf':(29,3,0),'rd':(7,5,1),'vd':(7,5,8),'vs3':(7,5,8),
        'vs1':(15,5,24),'vs2':(20,5,16),'rs1':(15,5,2),'rs2':(20,5,3),
        'vm':(25,1,1),'simm5':(15,5,1),'zimm5':(15,5,2),
        'zimm10':(20,10,0),'zimm11':(20,11,0)}

def generate():
    source=HERE/'vendor/riscv-opcodes/rv_v'
    lines=['// Generated by generate_catalog.py; see vendor/riscv-opcodes/LICENSE.',
           '// Source SHA256: '+hashlib.sha256(source.read_bytes()).hexdigest(),
           '#pragma once',
           'struct CatalogEntry { const char* name; uint32_t insn; bool segment, mask; };',
           'static const CatalogEntry vector_catalog[]={']
    names=set()
    for raw in source.read_text().splitlines():
        words=raw.split('#')[0].split()
        if not words:continue
        name,*tokens=words
        if name in names:raise ValueError('Duplicate name '+name)
        names.add(name);insn=0;used=0
        for token in tokens:
            if '=' in token:
                bits,value=token.split('=');value=int(value,0)
                parts=[int(b) for b in bits.split('..')]
                high,low=(parts[0],parts[-1]);width=high-low+1
            else:low,width,value=FIELDS[token]
            mask=((1<<width)-1)<<low
            if used&mask or value<0 or value>=1<<width:
                raise ValueError('Invalid/overlapping field '+raw)
            used|=mask;insn|=value<<low
        if used!=0xffffffff:raise ValueError('Unspecified bits '+raw)
        lines.append('  {"%s",0x%08xu,%s,%s},'%(name,insn,
                     str('nf' in tokens).lower(),str('vm' in tokens).lower()))
    if len(names)!=375:raise ValueError('Catalog changed; review baseline scope')
    return '\n'.join(lines+['};',''])

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true');args=parser.parse_args()
    output=HERE/'catalog_entries.h';content=generate()
    if args.check:
        if output.read_text()!=content:raise SystemExit('Stale catalog_entries.h')
        print('PASS catalog generation: 375 entries')
    else:output.write_text(content)
