#!/usr/bin/env python3
"""Embed Linux stage0/DTB/OpenSBI fixes in LiteX BIOS SD-card boot.

The SD card may keep an older contiguous boot.bin.  After LiteX BIOS copies it
to main RAM, the injected hook replaces stage0 and the DTB slot, then patches
the release OpenSBI header to keep its FDT relocation outside the Linux Image.
The large Linux payload remains the one read from the card.
"""

from __future__ import annotations

import argparse
import re
import shutil
import struct
import sys
from pathlib import Path


INCLUDE_ANCHOR = "#include <libfatfs/ff.h>\n"
BOOT_ANCHOR = """static void sdcardboot_from_bin(const char * filename)
{
\tuint32_t result;
\tresult = copy_file_from_sdcard_to_ram(filename, MAIN_RAM_BASE_VA, MAIN_RAM_SIZE);
\tif (result == 0)
\t\treturn;
\tboot(0, 0, 0, MAIN_RAM_BASE_VA);
}
"""
MARKER = "RAPTOR_SDCARD_LINUX_OVERRIDE"
END_MARKER = f"/* END_{MARKER} */\n"
FATFS_BOOT_ANCHOR = """static void fatfsboot_from_bin(const char *filename)
{
\tsize_t size;
\tsize_t max_size;

\tif (!boot_load_max_size(MAIN_RAM_BASE_VA, &max_size))
\t\treturn;
\tif (fatfs_load_file(filename, (void *)MAIN_RAM_BASE_VA, max_size,
\t\t&size, 1) != BOOT_LOAD_OK)
\t\treturn;
\tboot(0, 0, 0, MAIN_RAM_BASE_VA);
}
"""
BOOT_ANCHORS = (BOOT_ANCHOR, FATFS_BOOT_ANCHOR)


def patch_boot(anchor: str) -> str:
    return anchor.replace(
    "\tboot(0, 0, 0, MAIN_RAM_BASE_VA);",
    "\traptor_sdcard_linux_override();\n"
    "\tif (!raptor_patch_opensbi_fdt_relocation())\n"
    "\t\treturn;\n"
    "\tboot(0, 0, 0, MAIN_RAM_BASE_VA);",
    )


PATCHED_BOOT = patch_boot(BOOT_ANCHOR)
FDT_MAGIC = 0xD00DFEED
RISCV_LUI_A1_MASK = 0x00000FFF
RISCV_LUI_A1_BITS = 0x000005B7
RISCV_ADD_A0_A0_A1 = 0x00B50533
RISCV_RET = 0x00008067


def remove_generated_override(source: str) -> str:
    """Refresh our generated data without discarding other BIOS edits.

    Also accept the original patch format, which had no end marker. Its
    final generated function provides a bounded migration anchor.
    """
    begin = f"\n/* {MARKER}: generated by Raptor's build wrapper. */\n"
    if begin not in source:
        if MARKER in source:
            raise ValueError("unrecognized Linux override marker")
        return source
    matches = [anchor for anchor in BOOT_ANCHORS if source.count(patch_boot(anchor)) == 1]
    if source.count(begin) != 1 or len(matches) != 1:
        raise ValueError("Linux override anchors must occur exactly once")
    start = source.index(begin)
    end = source.find(END_MARKER, start)
    if end >= 0:
        end += len(END_MARKER)
    else:
        match = re.search(
            r"\nstatic void raptor_sdcard_linux_override\(void\)\n\{.*?\n\}\n",
            source[start:], re.DOTALL,
        )
        if match is None:
            raise ValueError("incomplete legacy Linux override block")
        end = start + match.end()
    anchor = matches[0]
    return (source[:start] + source[end:]).replace(patch_boot(anchor), anchor)


def c_array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("\t" + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};\n"


def parse_offset(value: str) -> int:
    try:
        offset = int(value, 0)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid integer: {value}") from exc
    if offset <= 0 or offset > 0xFFFFFFFF:
        raise argparse.ArgumentTypeError("address/offset must be in 1..0xffffffff")
    return offset


def encode_lui_a1(value: int) -> int:
    if value < 0 or value > 0x7FFFFFFF or value & 0xFFF:
        raise ValueError("OpenSBI FDT offset must be positive and 4 KiB aligned")
    return (value & 0xFFFFF000) | RISCV_LUI_A1_BITS


def find_opensbi_fdt_lui(payload: bytes) -> tuple[int, int]:
    """Locate fw_next_arg1's ``lui a1, <FDT offset>`` instruction."""
    offset, lui, _ = find_opensbi_fdt_sequence(payload)
    return offset, lui


def find_opensbi_fdt_sequence(payload: bytes) -> tuple[int, int, bytes]:
    """Accept standard/compressed ADD and RET, including halfword alignment.

    Only these exact instruction sequences are supported. Unknown or ambiguous
    firmware still fails closed; never skip the relocation compatibility check.
    """
    candidates: list[tuple[int, int]] = []
    limit = min(len(payload), 0x100000)
    for offset in range(0, limit - 8 + 1, 2):
        lui = struct.unpack_from("<I", payload, offset)[0]
        if lui & RISCV_LUI_A1_MASK != RISCV_LUI_A1_BITS:
            continue
        for add in (struct.pack("<I", RISCV_ADD_A0_A0_A1), b"\x2e\x95"):
            for ret in (struct.pack("<I", RISCV_RET), b"\x82\x80"):
                tail = add + ret
                if payload[offset + 4:min(limit, offset + 4 + len(tail))] == tail:
                    candidates.append((offset, lui, tail))
    if len(candidates) != 1:
        raise ValueError(
            "expected exactly one OpenSBI fw_next_arg1 LUI sequence in the "
            f"first 1 MiB, found {len(candidates)}"
        )
    return candidates[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("litex_root", type=Path)
    parser.add_argument("stage0", type=Path)
    parser.add_argument("dtb", type=Path)
    parser.add_argument("payload", type=Path)
    parser.add_argument("payload_offset", type=parse_offset)
    parser.add_argument("dtb_offset", type=parse_offset)
    parser.add_argument("dtb_address", type=parse_offset)
    parser.add_argument("main_ram_base", type=parse_offset)
    parser.add_argument("--output-dir", type=Path,
                        help="Stage a private BIOS source tree instead of editing LiteX")
    args = parser.parse_args()

    boot_c = args.litex_root / "litex/soc/software/bios/boot.c"
    try:
        source = boot_c.read_text()
        stage0 = args.stage0.read_bytes()
        dtb = args.dtb.read_bytes()
        payload = args.payload.read_bytes()
    except OSError as exc:
        print(f"[patch_litex_sdcard_linux_override] error: {exc}", file=sys.stderr)
        return 1

    try:
        source = remove_generated_override(source)
    except ValueError as exc:
        print(f"[patch_litex_sdcard_linux_override] error: {exc}", file=sys.stderr)
        return 1
    matches = [anchor for anchor in BOOT_ANCHORS if source.count(anchor) == 1]
    if source.count(INCLUDE_ANCHOR) != 1 or len(matches) != 1:
        print(
            "[patch_litex_sdcard_linux_override] expected LiteX BIOS anchors "
            f"not found exactly once: {boot_c}",
            file=sys.stderr,
        )
        return 1
    if not stage0 or len(stage0) > 0x100000:
        print(
            f"[patch_litex_sdcard_linux_override] invalid stage0 size: {len(stage0)}",
            file=sys.stderr,
        )
        return 1
    if len(dtb) < 40 or struct.unpack_from(">I", dtb, 0)[0] != FDT_MAGIC:
        print("[patch_litex_sdcard_linux_override] invalid DTB", file=sys.stderr)
        return 1
    if struct.unpack_from(">I", dtb, 4)[0] != len(dtb):
        print(
            "[patch_litex_sdcard_linux_override] DTB file has trailing or missing bytes",
            file=sys.stderr,
        )
        return 1
    if args.dtb_address <= args.main_ram_base:
        print(
            "[patch_litex_sdcard_linux_override] DTB address must be above main RAM base",
            file=sys.stderr,
        )
        return 1
    try:
        opensbi_patch_offset, opensbi_old_lui, opensbi_tail = find_opensbi_fdt_sequence(payload)
        opensbi_new_lui = encode_lui_a1(args.dtb_address - args.main_ram_base)
    except ValueError as exc:
        print(f"[patch_litex_sdcard_linux_override] error: {exc}", file=sys.stderr)
        return 1
    opensbi_old_fdt_address = args.main_ram_base + (opensbi_old_lui & 0xFFFFF000)

    embedded = f"""
/* {MARKER}: generated by Raptor's build wrapper. */
{c_array("raptor_linux_stage0", stage0)}
{c_array("raptor_linux_dtb", dtb)}
{c_array("raptor_opensbi_expected", struct.pack("<I", opensbi_old_lui) + opensbi_tail)}
{c_array("raptor_opensbi_patched", struct.pack("<I", opensbi_new_lui) + opensbi_tail)}
static int raptor_patch_opensbi_fdt_relocation(void)
{{
\tvolatile uint8_t *patch = (volatile uint8_t *)(uintptr_t)
\t\t(MAIN_RAM_BASE_VA + 0x{args.payload_offset + opensbi_patch_offset:08x}UL);
\tunsigned int i;
\tint original = 1, patched = 1;
\tfor (i = 0; i < sizeof(raptor_opensbi_expected); i++) {{
\t\toriginal &= patch[i] == raptor_opensbi_expected[i];
\t\tpatched &= patch[i] == raptor_opensbi_patched[i];
\t}}
\tif (!original && !patched) {{
\t\tprintf("Raptor: SD OpenSBI header mismatch; refusing unsafe boot\\n");
\t\treturn 0;
\t}}
\t/* Byte writes also support a LUI at an address aligned to only 2 bytes. */
\tfor (i = 0; i < 4; i++)
\t\tpatch[i] = raptor_opensbi_patched[i];
\tprintf("Raptor: patched OpenSBI FDT relocation 0x{opensbi_old_fdt_address:08x}"
\t       " -> 0x{args.dtb_address:08x}\\n");
\treturn 1;
}}

static void raptor_sdcard_linux_override(void)
{{
\tmemcpy((void *)(uintptr_t)MAIN_RAM_BASE_VA,
\t\traptor_linux_stage0, sizeof(raptor_linux_stage0));
\tmemcpy((void *)(uintptr_t)(MAIN_RAM_BASE_VA + 0x{args.dtb_offset:08x}UL),
\t\traptor_linux_dtb, sizeof(raptor_linux_dtb));
\tprintf("Raptor: replaced SD stage0 (%lu bytes) and DTB (%lu bytes)\\n",
\t\t(unsigned long)sizeof(raptor_linux_stage0),
\t\t(unsigned long)sizeof(raptor_linux_dtb));
}}
""" + END_MARKER
    source = source.replace(INCLUDE_ANCHOR, INCLUDE_ANCHOR + embedded)
    source = source.replace(matches[0], patch_boot(matches[0]))
    try:
        if args.output_dir is not None:
            if args.output_dir.resolve().is_relative_to(boot_c.parent.resolve()):
                raise ValueError("--output-dir must be a private BIOS directory")
            shutil.copytree(boot_c.parent, args.output_dir, dirs_exist_ok=True)
            boot_c = args.output_dir / "boot.c"
        boot_c.write_text(source)
    except (OSError, ValueError) as exc:
        print(f"[patch_litex_sdcard_linux_override] error: {exc}", file=sys.stderr)
        return 1

    print(
        f"[patch_litex_sdcard_linux_override] embedded stage0={len(stage0)} "
        f"DTB={len(dtb)} offset=0x{args.dtb_offset:x}; OpenSBI patch "
        f"payload+0x{opensbi_patch_offset:x}: 0x{opensbi_old_fdt_address:x} -> "
        f"0x{args.dtb_address:x}: {boot_c}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
