"""Check supported LiteX boot hooks and preservation of unrelated edits."""
import pathlib
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "scripts"))
import patch_litex_sdcard_linux_override as override


class BootHookTest(unittest.TestCase):
    def test_old_and_new_hooks_roundtrip(self):
        for anchor in override.BOOT_ANCHORS:
            original = "/* user edit */\n" + override.INCLUDE_ANCHOR + anchor
            generated = (f"\n/* {override.MARKER}: generated by Raptor's build wrapper. */\n"
                         "/* placeholder data */\n" + override.END_MARKER)
            patched = original.replace(override.INCLUDE_ANCHOR,
                                       override.INCLUDE_ANCHOR + generated)
            patched = patched.replace(anchor, override.patch_boot(anchor))
            self.assertEqual(override.remove_generated_override(patched), original)

    def test_current_source_has_one_supported_hook(self):
        repo = pathlib.Path(__file__).resolve().parents[3]
        source = (repo / "third_party/enjoy-digital/litex/litex/soc/software/bios/boot.c").read_text()
        source = override.remove_generated_override(source)
        self.assertEqual(sum(source.count(a) for a in override.BOOT_ANCHORS), 1)

    def test_unknown_marker_rejected(self):
        with self.assertRaises(ValueError):
            override.remove_generated_override(override.MARKER)


if __name__ == "__main__":
    unittest.main()
