// Generated by CIRCT firtool-1.62.0
module CSRDecoder (  // @[src/main/GCD.scala:8:7]
    input         clock,               // @[src/main/GCD.scala:8:7]
    reset,  // @[src/main/GCD.scala:8:7]
    input  [31:0] instruction,         // @[src/main/GCD.scala:33:23]
    output        system_func3_zero_o, // @[src/main/GCD.scala:34:31]
    csr_wen_o,  // @[src/main/GCD.scala:35:21]
    system_o  // @[src/main/GCD.scala:36:20]
);

  wire [29:0] decoded_invInputs = ~(instruction[31:2]);	// @[src/main/GCD.scala:33:23, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [31:0] _decoded_andMatrixOutputs_T = {
    instruction[0],
    instruction[1],
    decoded_invInputs[0],
    decoded_invInputs[1],
    instruction[4],
    instruction[5],
    instruction[6],
    decoded_invInputs[5],
    decoded_invInputs[6],
    decoded_invInputs[7],
    decoded_invInputs[8],
    decoded_invInputs[9],
    decoded_invInputs[10],
    decoded_invInputs[11],
    decoded_invInputs[12],
    decoded_invInputs[13],
    decoded_invInputs[14],
    decoded_invInputs[15],
    decoded_invInputs[16],
    decoded_invInputs[17],
    decoded_invInputs[18],
    decoded_invInputs[19],
    decoded_invInputs[20],
    decoded_invInputs[21],
    decoded_invInputs[22],
    decoded_invInputs[23],
    decoded_invInputs[24],
    decoded_invInputs[25],
    decoded_invInputs[26],
    decoded_invInputs[27],
    decoded_invInputs[28],
    decoded_invInputs[29]
  };  // @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [7:0] _decoded_andMatrixOutputs_T_2 = {
    instruction[0],
    instruction[1],
    decoded_invInputs[0],
    decoded_invInputs[1],
    instruction[4],
    instruction[5],
    instruction[6],
    instruction[12]
  };  // @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [7:0] _decoded_andMatrixOutputs_T_3 = {
    instruction[0],
    instruction[1],
    decoded_invInputs[0],
    decoded_invInputs[1],
    instruction[4],
    instruction[5],
    instruction[6],
    instruction[13]
  };  // @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [31:0] _decoded_andMatrixOutputs_T_4 = {
    instruction[0],
    instruction[1],
    decoded_invInputs[0],
    decoded_invInputs[1],
    instruction[4],
    instruction[5],
    instruction[6],
    decoded_invInputs[5],
    decoded_invInputs[6],
    decoded_invInputs[7],
    decoded_invInputs[8],
    decoded_invInputs[9],
    decoded_invInputs[10],
    decoded_invInputs[11],
    decoded_invInputs[12],
    decoded_invInputs[13],
    decoded_invInputs[14],
    decoded_invInputs[15],
    decoded_invInputs[16],
    decoded_invInputs[17],
    decoded_invInputs[18],
    instruction[21],
    decoded_invInputs[20],
    decoded_invInputs[21],
    decoded_invInputs[22],
    decoded_invInputs[23],
    decoded_invInputs[24],
    decoded_invInputs[25],
    instruction[28],
    instruction[29],
    decoded_invInputs[28],
    decoded_invInputs[29]
  };  // @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  assign system_func3_zero_o =
    |{&_decoded_andMatrixOutputs_T, &_decoded_andMatrixOutputs_T_4};	// @[src/main/GCD.scala:8:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign csr_wen_o =
    |{&_decoded_andMatrixOutputs_T,
      &_decoded_andMatrixOutputs_T_2,
      &_decoded_andMatrixOutputs_T_3,
      &_decoded_andMatrixOutputs_T_4};	// @[src/main/GCD.scala:8:7, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  assign system_o =
    |{&_decoded_andMatrixOutputs_T,
      &{instruction[0],
        instruction[1],
        instruction[2],
        instruction[3],
        decoded_invInputs[2],
        decoded_invInputs[3],
        decoded_invInputs[4],
        instruction[12],
        decoded_invInputs[11],
        decoded_invInputs[12]},
      &_decoded_andMatrixOutputs_T_2,
      &_decoded_andMatrixOutputs_T_3,
      &_decoded_andMatrixOutputs_T_4};	// @[src/main/GCD.scala:8:7, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
endmodule

