/* rv_compressed.c: Test C (compressed) extension instructions */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define CHECK(cond, msg) do { \
    if (!(cond)) { printf("FAIL: %s (line %d)\n", msg, __LINE__); fail++; } \
    else { pass++; } \
} while (0)

/*
 * C extension instructions are transparently generated by the compiler.
 * Verify they produce correct results by testing patterns that typically
 * emit compressed instructions (c.addi, c.li, c.lui, c.mv, c.add,
 * c.beqz, c.bnez, c.j, c.lw, c.sw, etc.).
 */

static volatile int sink;

__attribute__((noinline))
int add_small(int a) {
    /* c.addi pattern */
    return a + 1;
}

__attribute__((noinline))
int load_immediate(void) {
    /* c.li pattern */
    return 15;
}

__attribute__((noinline))
int move_reg(int a) {
    /* c.mv pattern */
    int b = a;
    sink = b;
    return b;
}

__attribute__((noinline))
int branch_zero(int a) {
    /* c.beqz / c.bnez patterns */
    if (a == 0) return 1;
    return 0;
}

__attribute__((noinline))
int stack_ops(int a, int b, int c, int d) {
    /* c.lwsp / c.swsp patterns (stack load/store) */
    volatile int va = a;
    volatile int vb = b;
    volatile int vc = c;
    volatile int vd = d;
    return va + vb + vc + vd;
}

__attribute__((noinline))
int shift_small(int a) {
    /* c.slli pattern */
    return a << 3;
}

int main(void) {
    int pass = 0, fail = 0;

    CHECK(add_small(10) == 11, "c.addi: 10 + 1 = 11");
    CHECK(add_small(-1) == 0, "c.addi: -1 + 1 = 0");
    CHECK(load_immediate() == 15, "c.li: load 15");
    CHECK(move_reg(42) == 42, "c.mv: copy 42");
    CHECK(branch_zero(0) == 1, "c.beqz: 0 is zero");
    CHECK(branch_zero(5) == 0, "c.bnez: 5 is not zero");
    CHECK(stack_ops(1, 2, 3, 4) == 10, "c.lwsp/swsp: 1+2+3+4=10");
    CHECK(shift_small(1) == 8, "c.slli: 1 << 3 = 8");

    /* Verify compressed instruction alignment:
     * RV32C allows 2-byte aligned instructions, so a function
     * address can be 2-byte aligned (not necessarily 4-byte) */
    {
        uintptr_t addr = (uintptr_t)&add_small;
        CHECK((addr & 1) == 0, "function address is 2-byte aligned");
    }

    /* Test tight loop with compressed instructions */
    {
        volatile int sum = 0;
        for (int i = 0; i < 100; i++)
            sum += i;
        CHECK(sum == 4950, "tight loop: sum(0..99) = 4950");
    }

    printf("rv_compressed: %d passed, %d failed\n", pass, fail);
    return fail ? EXIT_FAILURE : EXIT_SUCCESS;
}
