name: AM CPU ISA tests (difftest)

on:
  push:
    branches: ["master", "main"]
    paths:
      - "rtl_sv/**"
      - "rtl_scala/**"
      - "nsim/**"
      - "abstract-machine/**"
      - "am-kernels/tests/cpu-tests/**"
      - ".github/workflows/am-*.yaml"
  pull_request:
    branches: ["master", "main"]
    paths:
      - "rtl_sv/**"
      - "rtl_scala/**"
      - "nsim/**"
      - "abstract-machine/**"
      - "am-kernels/tests/cpu-tests/**"
      - ".github/workflows/am-*.yaml"

jobs:
  npc-cpu-tests:
    runs-on: ubuntu-latest
    env:
      YSYX_HOME: ${{ github.workspace }}
      NEMU_HOME: ${{ github.workspace }}/nemu
      AM_HOME: ${{ github.workspace }}/abstract-machine
      CROSS_COMPILE: riscv64-elf-
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: ./setup.sh
      - name: Build NPC with difftest and NEMU-Ref
        shell: bash -l {0}
        run: |
          make config-npc32-difftest
          make config-nemu32-ref
      - name: cpu-tests riscv32e-npc
        shell: bash -l {0}
        run: make cpu-tests-npc32 NPC_ARCH=riscv32e-npc ARGS="-b -n"
      - name: cpu-tests riscv32-npc
        shell: bash -l {0}
        run: make cpu-tests-npc32 NPC_ARCH=riscv32-npc ARGS="-b -n"

  ysyxsoc-cpu-tests:
    runs-on: ubuntu-latest
    env:
      YSYX_HOME: ${{ github.workspace }}
      NEMU_HOME: ${{ github.workspace }}/nemu
      AM_HOME: ${{ github.workspace }}/abstract-machine
      CROSS_COMPILE: riscv64-elf-
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: ./setup.sh
      - name: Generate ysyxSoC
        shell: bash -l {0}
        run: make -C ./third_party/kingfish404/ysyxSoC/ dev-init verilog
      - name: Build NPC (ysyxSoC config) and NEMU-Ref
        shell: bash -l {0}
        run: |
          make config-npc32-ysyxsoc
          make config-nemu32-ref
      - name: cpu-tests riscv32-ysyxsoc
        shell: bash -l {0}
        run: make -C $YSYX_HOME/am-kernels/tests/cpu-tests ARCH=riscv32-ysyxsoc run ARGS="-b -n"
      - name: cpu-tests riscv32e-ysyxsoc
        shell: bash -l {0}
        run: make -C $YSYX_HOME/am-kernels/tests/cpu-tests ARCH=riscv32e-ysyxsoc run ARGS="-b -n"
